### ISSUE TITLE
找不到资源ID

### ISSUE THREAD

**Issue by yq2yizi** [Timmy-zzh/TDialog#15]
第一步:
 public <T extends View> T getView(@IdRes int viewId) {
        View view = views.get(viewId);
        if (view == null) {
            view = bindView.findViewById(viewId);
            views.put(viewId, view);
        }
        return (T) view;
    }
第二步
 public BindViewHolder setText(@IdRes int viewId, CharSequence value) {
        TextView view = getView(viewId);
        if (view != null) view.setText(value);
        return this;
    }

第三步
   .setOnBindViewListener(new OnBindViewListener() {
                        @Override
                        public void bindView(BindViewHolder bindViewHolder) {
                            bindViewHolder.setText(R.id.txt_order_evaluate_point_name, "xxx");
//                            bindViewHolder.setText(R.id.txt_order_evaluate_point_value, bean.data.rewardPoint);
//                            bindViewHolder.setText(R.id.txt_order_evaluate_vip_value, bean.data.rewardVip);
//                            bindViewHolder.setText(R.id.txt_order_evaluate_point_notice1, "高等级用户享受更多隐藏福利");
//                            bindViewHolder.setText(R.id.txt_order_evaluate_vip_name, "zzz");
                        }   //通过BindViewHolder拿到控件对象,进行修改

                    })

 异常: bindViewHolder.setText(R.id.txt_order_evaluate_point_name, "xxx"); 这句话,直接崩了.

布局:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="center_vertical"
    android:background="@drawable/shape_order_evaluate_dialog_yellow_bg">

    <TextView
        android:id="@+id/txt_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_gravity="center_horizontal"
        android:layout_marginBottom="@dimen/px30"
        android:layout_marginTop="@dimen/px40"
        android:text="恭喜获得礼包"
        android:textColor="@color/black"
        android:textSize="@dimen/font_32px"/>

    <RelativeLayout
        android:id="@+id/order_evaluate_dialog_title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/txt_title">

        <View
            android:id="@+id/dialog_view_divider1"
            android:layout_width="match_parent"
            android:layout_height="@dimen/px1"
            android:layout_marginLeft="@dimen/px20"
            android:layout_marginTop="@dimen/px20"
            android:layout_toLeftOf="@+id/txt_order_evaluate_sub_title"
            android:background="@color/black"/>

        <TextView
            android:id="@+id/txt_order_evaluate_sub_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            android:layout_margin="@dimen/px5"
            android:text="本次获得"
            android:textColor="@color/black"/>

        <View
            android:id="@+id/dialog_view_divider2"
            android:layout_width="match_parent"
            android:layout_height="@dimen/px1"
            android:layout_marginBottom="@dimen/px10"
            android:layout_marginRight="@dimen/px20"
            android:layout_marginTop="@dimen/px20"
            android:layout_toRightOf="@+id/txt_order_evaluate_sub_title"
            android:background="@color/black"/>
    </RelativeLayout>

    
    
    
    
    

    <RelativeLayout
        android:id="@+id/rl_point"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/order_evaluate_dialog_title"
        android:layout_marginBottom="@dimen/px10"
        android:layout_marginLeft="@dimen/px20"
        android:layout_marginRight="@dimen/px20"
        android:layout_marginTop="@dimen/px20"
        android:background="@drawable/shape_order_evaluate_dialog_white_bg"
        >

        <TextView
            android:id="@+id/txt_order_evaluate_point_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="@dimen/px30"
            android:layout_marginLeft="@dimen/px40"
            android:layout_marginTop="@dimen/px40"
            android:textColor="@color/black"
            android:textSize="@dimen/font_40px"/>

        <TextView
            android:id="@+id/txt_order_evaluate_point_value"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_marginBottom="@dimen/px30"
            android:layout_marginLeft="@dimen/px40"
            android:layout_marginRight="@dimen/px40"
            android:layout_marginTop="@dimen/px45"
            android:text="10元"
            android:textColor="@color/black"
            android:textSize="@dimen/font_32px"/>

        <TextView
            android:id="@+id/txt_order_evaluate_point_notice1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_below="@+id/txt_order_evaluate_point_value"
            android:layout_marginBottom="@dimen/px30"
            android:layout_marginLeft="@dimen/px40"
            android:layout_marginRight="@dimen/px40"
            android:layout_marginTop="@dimen/px40"
            android:textColor="@color/didi_seller_def_bg"
            android:textSize="@dimen/font_34px"/>
    </RelativeLayout>

    <RelativeLayout
        android:id="@+id/rl_vip"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/rl_point"
        android:layout_marginBottom="@dimen/px20"
        android:layout_marginLeft="@dimen/px20"
        android:layout_marginRight="@dimen/px20"
        android:layout_marginTop="@dimen/px10"
        android:background="@drawable/shape_order_evaluate_dialog_white_bg"
        >

        <TextView
            android:id="@+id/txt_order_evaluate_vip_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="@dimen/px30"
            android:layout_marginLeft="@dimen/px40"
            android:layout_marginTop="@dimen/px40"
            android:textColor="@color/black"
            android:textSize="@dimen/font_40px"/>

        <TextView
            android:id="@+id/txt_order_evaluate_vip_value"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_marginBottom="@dimen/px30"
            android:layout_marginLeft="@dimen/px40"
            android:layout_marginRight="@dimen/px40"
            android:layout_marginTop="@dimen/px45"
            android:text="10元"
            android:textColor="@color/black"
            android:textSize="@dimen/font_32px"/>

        <TextView
            android:id="@+id/txt_order_evaluate_vip_notice1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_below="@+id/txt_order_evaluate_vip_value"
            android:layout_marginBottom="@dimen/px30"
            android:layout_marginLeft="@dimen/px40"
            android:layout_marginRight="@dimen/px40"
            android:layout_marginTop="@dimen/px40"
            android:textColor="@color/didi_seller_def_bg"
            android:textSize="@dimen/font_34px"/>
    </RelativeLayout>

    <Button
        android:id="@+id/order_evaluate_bt"
        android:layout_width="match_parent"
        android:layout_height="@dimen/px98"
        android:layout_below="@+id/rl_vip"
        android:background="@color/white"
        android:text="点击领取"/>

</RelativeLayout>

也没有嵌套太深,但是一直找不到资源id.从你wiki里面直接copy然后设置这个布局也是会崩
我只是为了tdialog支持GridManager,修改了TListDialog的源码,也就只是添加了个字段.

**Comment by Timmy-zzh** [comment]
不好意思,最近事情太多了,请问问题解决了吗?
