### ISSUE TITLE
动态高度怎么设置？

### ISSUE THREAD

**Issue by zwping** [Timmy-zzh/TDialog#16]
目前TDialog设置高度只能设置固定值，怎么设置max值呢？低于max值就为当前高度，高于的话就自行滑动

**Comment by Timmy-zzh** [comment]
弹窗的高度在代码中你不用给值,高度就是warp_content,这个时候你在xml布局中就可以实现你想要的效果了

**Comment by zwping** [comment]
warp_content实现的是动态高度，实际需求是动态高度+最大高度

**Comment by Timmy-zzh** [comment]
自定义控件重写onMeasure()方法实现
