### ISSUE TITLE
兄弟你使用了几个构建工具，科学上网下载半天也没反应

### ISSUE THREAD

**Issue by zuojianjian** [Timmy-zzh/TDialog#2]
再好的项目让使用者摸不着头脑，或者太麻烦的构建方式，都没人看了，maven2真心下载不下来

**Comment by Timmy-zzh** [comment]
项目是放在jcenter仓库中,你看下你项目的gradle中是否有jcenter依赖
    repositories {
        ...
        jcenter()
    }
